for /R %%a IN (*.cs) do IF EXIST "%%a" del "%%a"
for /R %%a IN (*.cs) do IF EXIST "%%a" del "%%a"
for /R %%a IN (*.gui) do IF EXIST "%%a" del "%%a"
for /R %%a IN (*.gui) do IF EXIST "%%a" del "%%a"
for /R %%a IN (*.ts) do IF EXIST "%%a" del "%%a"
for /R %%a IN (*.ts) do IF EXIST "%%a" del "%%a"
